local r = require
r 'themaspai.core.keymaps'
r 'themaspai.core.options'
r 'themaspai.plugins.lazy'
r 'themaspai.plugins.nvim-tree'
r 'themaspai.plugins.nvim-web-devicons'
r 'themaspai.plugins.telescope'
r 'themaspai.plugins.nvim-treesitter'
r 'themaspai.plugins.mason-lspconfig'
r 'themaspai.plugins.nvim-cmp'
r 'themaspai.plugins.dap-go'
r 'themaspai.plugins.dapui'
r 'themaspai.plugins.toggleterm'
r 'themaspai.plugins.nvim-dap-virtual-text'
r 'themaspai.plugins.autopairs'
r 'themaspai.plugins.nvim-code-action-menu'
r 'themaspai.plugins.autoformat'
