add_newline = true
[directory]
truncation_length = 5
format = " [$path]($style)[$lock_symbol]($lock_style) "

[character]
success_symbol = '[λ](bold green)' 
error_symbol = '[λ](bold red)' 

[package]
disabled = true

[gcloud] 
disabled = true
